# Default values for spring-k8s-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


general:
  ingress: spring-demo.remi-pace.fr
  profile: dev
  microcomm:
    context: k8sdemo

nats:
  replicaCount: 1
  image:
    repository: nats
    tag: 1.1.0-linux
    pullPolicy: IfNotPresent


mongodb:
  replicaCount: 1
  image:
    repository: mvertes/alpine-mongo
    tag: 3.6.4-2
    pullPolicy: IfNotPresent


signatureService:
  replicaCount: 2
  image:
    repository: registry.gitlab.com/remipassmoilesel/spring-k8s-demo/k8sdemo.signature-service
    tag: 0.1
    pullPolicy: Always


gateway:
  replicaCount: 2
  image:
    repository: registry.gitlab.com/remipassmoilesel/spring-k8s-demo/k8sdemo.gateway
    tag: 0.1
    pullPolicy: Always

