apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-demo
  labels:
    app: spring-k8s-demo
spec:
  type: ClusterIP
  ports:
    - port: 8085
      protocol: TCP
      name: http
      targetPort: 8085
  selector:
    app: spring-k8s-demo
