- name: Add mongodb apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

- name: Add mongodb repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
    state: present

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Configure mongodb listen interface
  lineinfile:
    dest: /etc/mongod.conf
    line: "  bindIp: 0.0.0.0"
    regexp: "^  bindIp: (0.0.0.0|127.0.0.1)"

- name: Restart Mongodb
  systemd:
    name: mongod
    state: restarted
    enabled: yes


