apiVersion: v1
kind: Service
metadata:
  name: nats-{{ template "spring-k8s-demo.fullname" . }}
  labels:
    app: nats-{{ template "spring-k8s-demo.name" . }}
    chart: {{ template "spring-k8s-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: nats
      protocol: TCP
      name: nats
  selector:
    app: nats-{{ template "spring-k8s-demo.name" . }}
    release: {{ .Release.Name }}
