apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: signature-service-{{ template "spring-k8s-demo.fullname" . }}
  labels:
    app: signature-service-{{ template "spring-k8s-demo.name" . }}
    chart: {{ template "spring-k8s-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.signatureService.replicaCount }}
  selector:
    matchLabels:
      app: signature-service-{{ template "spring-k8s-demo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: signature-service-{{ template "spring-k8s-demo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.signatureService.image.repository }}:{{ .Values.signatureService.image.tag }}"
          imagePullPolicy: {{ .Values.signatureService.image.pullPolicy }}
          env:
          - name: SIGNATURE_SERV_ACTIVE_PROFILE
            value: {{ .Values.general.profile }}
          - name: SIGNATURE_SERV_DB_URI
            value: mongodb://mongodb-{{ template "spring-k8s-demo.name" . }}:27017
          - name: SKD_MICROCOMM_CONTEXT
            value: {{ .Values.general.microcomm.context }}
          - name: SKD_MICROCOMM_NATS_URL
            value: nats://nats-{{ template "spring-k8s-demo.fullname" . }}:4222
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
      - name: registry-secret
