version: '3'

# TODO: add container and volume for spring-boot application and sources

services:
  mariadb:
    image: mariadb:10.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db1
      MYSQL_USER: db1
      MYSQL_PASSWORD: db1
    ports:
     - 3306:3306
    networks:
      spring-k8s-demo-dev-network:
        aliases:
        - mariadb.docker.net

  nats:
    image: nats:1.1.0-linux
    entrypoint: "/gnatsd -DV"
    ports:
      - 8222:8222
      - 4222:4222
    networks:
      spring-k8s-demo-dev-network:
        aliases:
        - nats.docker.net

networks:
  spring-k8s-demo-dev-network: