apiVersion: v1
kind: Service
metadata:
    name: mongodb-{{ template "spring-k8s-demo.fullname" . }}
    labels:
        app: mongodb-{{ template "spring-k8s-demo.name" . }}
        chart: {{ template "spring-k8s-demo.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    type: ClusterIP
    ports:
        - port: 27017
          targetPort: mongodb
          protocol: TCP
          name: mongodb
    selector:
        app: mongodb-{{ template "spring-k8s-demo.name" . }}
        release: {{ .Release.Name }}
