apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb-{{ template "spring-k8s-demo.fullname" . }}
    labels:
        app: mongodb-{{ template "spring-k8s-demo.name" . }}
        chart: {{ template "spring-k8s-demo.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    replicas: {{ .Values.nats.replicaCount }}
    selector:
        matchLabels:
            app: mongodb-{{ template "spring-k8s-demo.name" . }}
            release: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app: mongodb-{{ template "spring-k8s-demo.name" . }}
                release: {{ .Release.Name }}
        spec:
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
                  imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
                  ports:
                      - name: mongodb
                        containerPort: 27017
                        protocol: TCP
                  livenessProbe:
                      tcpSocket:
                          port: 27017
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  readinessProbe:
                      tcpSocket:
                          port: 27017
                      initialDelaySeconds: 5
                      periodSeconds: 5
