apiVersion: v1
kind: Service
metadata:
  name: signatureService-{{ template "spring-k8s-demo.fullname" . }}
  labels:
    app: signatureService-{{ template "spring-k8s-demo.name" . }}
    chart: {{ template "spring-k8s-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: signatureService-{{ template "spring-k8s-demo.name" . }}
    release: {{ .Release.Name }}
