version: '3'

# TODO: add container and volume for spring-boot application and sources
# ... or use minikube ?

services:
  mongodb:
    image: mvertes/alpine-mongo:3.6.4-2
    restart: always
    ports:
     - 27017:27017
    networks:
      spring-k8s-demo-dev-network:
        aliases:
        - mongodb.docker.net

  nats:
    image: nats:1.1.0-linux
    entrypoint: "/gnatsd -m 8222 -D"
    ports:
      - 8222:8222
      - 4222:4222
    networks:
      spring-k8s-demo-dev-network:
        aliases:
        - nats.docker.net

networks:
  spring-k8s-demo-dev-network: