version: '3'

services:
  mongodb:
    container_name: skd-mongodb
    image: mvertes/alpine-mongo:3.6.4-2
    restart: always
    network_mode: host

  nats:
    container_name: skd-natsd
    image: nats:1.1.0-linux
    entrypoint: "/gnatsd -m 8222 -D"
    restart: always
    network_mode: host

  gateway:
    container_name: skd-gateway
    image: registry.gitlab.com/remipassmoilesel/spring-k8s-demo/gateway:0.1
    restart: always
    network_mode: host

  signature-service:
    container_name: skd-signature-service
    image: registry.gitlab.com/remipassmoilesel/spring-k8s-demo/signature-service:0.1
    restart: always
    network_mode: host
